version: '3.8'

services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ./eurica-service/eurica-service
    image: eureka-server:latest
    ports:
      - "8101:8101"
    networks:
      - my-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./ApiGateway/ApiGateway
    ports:
      - "8102:8102"
    depends_on:
      - eureka-server
    networks:
      - my-network

  user-service:
    container_name: userService
    build:
      context: ./UserService/UserService
    ports:
      - "8103:8103"
    depends_on:
      - eureka-server
    networks:
      - my-network

  dispatch-service:
    container_name: dispatchService
    build:
      context: ./DispatchService/DispatchService
    ports:
      - "8105:8105"
    depends_on:
      - eureka-server
    networks:
      - my-network

networks:
  my-network:
    driver: bridge