server :
  port : ${AUTH_SERVICE_APP_PORT}
  forward-headers-strategy: framework

spring:
  main:
    lazy-initialization: true
  application:
    name: authService
  datasource :
    url : ${AUTH_SERVICE_SQL_URL}
    username : ${POSTGRES_USER}
    password : ${POSTGRES_PASSWORD}
  jpa :
    open-in-view: false
    show-sql : true
    hibernate :
      ddl-auto : update


auth :
  api :
    key : ${API_INTERNAL_KEY}
  jwt :
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXP}


external:
  services:
    logging:
      base-url: ${LOGGING_SERVICE_URL}

logging:
  level:
    org.springframework.amqp: WARN
    com.rabbitmq: WARN
    org.springframework.security: DEBUG
    com.example.UserService: DEBUG


resilience4j:
  circuitbreaker:
    instances:
      myServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 15
        minimumNumberOfCalls: 10
        failureRateThreshold: 80
        waitDurationInOpenState: 22s
        permittedNumberOfCallsInHalfOpenState: 7
        automaticTransitionFromOpenToHalfOpenEnabled: true