-- AUTH DB
CREATE DATABASE "VEHICLE_AUTH_DB";
CREATE USER auth_user WITH PASSWORD 'auth_pass';
GRANT ALL PRIVILEGES ON DATABASE "VEHICLE_AUTH_DB" TO auth_user;

-- DISPATCH DB
CREATE DATABASE "VEHICLE_DISPATCH_DB";
CREATE USER dispatch_user WITH PASSWORD 'dispatch_pass';
GRANT ALL PRIVILEGES ON DATABASE "VEHICLE_DISPATCH_DB" TO dispatch_user;

-- VEHICLE DB
CREATE DATABASE "VEHICLE_VEHICLE_DB";
CREATE USER vehicle_user WITH PASSWORD 'vehicle_pass';
GRANT ALL PRIVILEGES ON DATABASE "VEHICLE_VEHICLE_DB" TO vehicle_user;
