/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./App.tsx", "./components/**/*.{js,jsx,ts,tsx}", "./screens/**/*.{js,jsx,ts,tsx}", 
"./contexts/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  
   darkMode: 'class', // Enable dark mode using the 'class' strategy
  theme: {
    extend: {
      borderRadius: {
        custom: '0.625rem',
      },
      colors: {
        background: 'hsl(210, 20%, 98%)',
        background2: 'hsl(210, 20%, 95%)',
        foreground: 'hsl(220, 13%, 8%)',
        card: 'hsl(0, 0%, 100%)',
        'card-foreground': 'hsl(0, 0%, 15%)',
        popover: 'hsl(0, 0%, 100%)',
        'popover-foreground': 'hsl(0, 0%, 15%)',
        primary: 'hsl(0, 0%, 20%)',
        'primary-foreground': 'hsl(0, 0%, 98%)',
        secondary: 'hsl(0, 0%, 97%)',
        'secondary-foreground': 'hsl(0, 0%, 20%)',
        muted: 'hsl(0, 0%, 97%)',
        'muted-foreground': 'hsl(0, 0%, 56%)',
        accent: 'hsl(0, 0%, 97%)',
        'accent-foreground': 'hsl(0, 0%, 20%)',
        destructive: 'hsl(27, 24%, 58%)',
        border: 'hsl(0, 0%, 92%)',
        input: 'hsl(0, 0%, 92%)',
        ring: 'hsl(0, 0%, 70%)',
        'chart-1': 'hsl(41, 22%, 65%)',
        'chart-2': 'hsl(184, 12%, 60%)',
        'chart-3': 'hsl(227, 7%, 40%)',
        'chart-4': 'hsl(84, 18%, 83%)',
        'chart-5': 'hsl(70, 18%, 77%)',
        sidebar: 'hsl(0, 0%, 98%)',
        'sidebar-foreground': 'hsl(0, 0%, 15%)',
        'sidebar-primary': 'hsl(0, 0%, 20%)',
        'sidebar-primary-foreground': 'hsl(0, 0%, 98%)',
        'sidebar-accent': 'hsl(0, 0%, 97%)',
        'sidebar-accent-foreground': 'hsl(0, 0%, 20%)',
        'sidebar-border': 'hsl(0, 0%, 92%)',
        'sidebar-ring': 'hsl(0, 0%, 70%)',
        // Dark mode colors
        dark: {
          background: 'hsl(210, 20%, 10%)',
          background2: 'hsl(210, 20%, 8%)',
          foreground: 'hsl(220, 13%, 95%)',
          card: 'hsl(0, 0%, 20%)',
          'card-foreground': 'hsl(0, 0%, 98%)',
          popover: 'hsl(0, 0%, 20%)',
          'popover-foreground': 'hsl(0, 0%, 98%)',
          primary: 'hsl(0, 0%, 92%)',
          'primary-foreground': 'hsl(0, 0%, 20%)',
          secondary: 'hsl(0, 0%, 27%)',
          'secondary-foreground': 'hsl(0, 0%, 98%)',
          muted: 'hsl(0, 0%, 27%)',
          'muted-foreground': 'hsl(0, 0%, 70%)',
          accent: 'hsl(0, 0%, 27%)',
          'accent-foreground': 'hsl(0, 0%, 98%)',
          destructive: 'hsl(22, 19%, 70%)',
          border: 'hsl(0, 0%, 100%, 10%)',
          input: 'hsl(0, 0%, 100%, 15%)',
          ring: 'hsl(0, 0%, 56%)',
          'chart-1': 'hsl(264, 24%, 49%)',
          'chart-2': 'hsl(162, 17%, 69%)',
          'chart-3': 'hsl(70, 18%, 77%)',
          'chart-4': 'hsl(303, 26%, 62%)',
          'chart-5': 'hsl(16, 24%, 64%)',
          sidebar: 'hsl(0, 0%, 20%)',
          'sidebar-foreground': 'hsl(0, 0%, 98%)',
          'sidebar-primary': 'hsl(264, 24%, 49%)',
          'sidebar-primary-foreground': 'hsl(0, 0%, 98%)',
          'sidebar-accent': 'hsl(0, 0%, 27%)',
          'sidebar-accent-foreground': 'hsl(0, 0%, 98%)',
          'sidebar-border': 'hsl(0, 0%, 100%, 10%)',
          'sidebar-ring': 'hsl(0, 0%, 56%)',
        },
      },
      spacing: {
        'xxs': 'min(2vw, 0.25rem)',
        'xs': 'min(4vw, 0.5rem)',
        'sm': 'min(6vw, 1rem)',
        'sm-1': 'min(6vw, 1.2rem)',
        'sm-2': 'min(6vw, 1.8rem)',
        'sm-3': 'min(6vw, 2rem)',
        'md': 'min(10vw, 3.2rem)',
        'md-2': 'min(10vw, 3.8rem)',
        'md-3': 'min(10vw, 4rem)',
        'lg': 'min(12vw, 6rem)',
        'xl': 'min(12vw, 8rem)',
        'xxl': 'min(12vw, 12rem)',
        'xxxl': 'min(14vw, 14rem)',
      },
      fontSize: {
        'xxs': 'min(2vw, 0.25rem)',
        'xs': 'min(2vw, 0.5rem)',
        'small': 'min(4vw, 0.8rem)',
        'body': 'min(4vw, 1rem)',
        'normal': 'min(6vw, 1.8rem)',
        'medium': 'min(8vw, 2rem)',
        'subheading': 'min(10vw, 2.8rem)',
        'heading': 'min(10vw, 4rem)',
        'large': 'min(14vw, 4.8rem)',
        'xlarge': 'min(16vw, 5.4rem)',
      },
      fontWeight: {
        thin: '100',
        light: '200',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        heavy: '900',
      },
      lineHeight: {
        tight: '1.2',
        normal: '1.5',
        loose: '1.6',
        looser: '1.8',
        loosest: '2',
      },
      fontFamily: {
        'futura-heavy': ['Futura Heavy', 'sans-serif'],
        'futura-medium': ['Futura Medium BT', 'sans-serif'],
        roboto: ['Roboto', 'sans-serif'],
      },
    },
  },


  plugins: [],
}