server:
  port: ${DISPATCH_SERVICE_APP_PORT}
  forward-headers-strategy: framework

spring:
  main:
    lazy-initialization: true
  application:
    name: dispatchService
  datasource:
    url: ${DISPATCH_SERVICE_SQL_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      initialization-fail-timeout: 60000
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_URL}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          multiplier: 2.0
          max-interval: 10000ms

auth:
  api:
    key: ${API_INTERNAL_KEY}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXP}
    issuer: auth-service

external:
  services:
    logging:
      base-url: ${LOGGING_SERVICE_URL}
    vehicle:
      base-url: ${VEHICLE_SERVICE_URL}
    auth:
      base-url: ${AUTH_SERVICE_URL}

messaging:
  type: ${MESSAGE_TYPE}

logging:
  level:
    org.springframework.amqp: WARN
    com.rabbitmq: WARN
    org.springframework.security: DEBUG
    com.example.DispatchService: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      vehicleServiceCircuit:
        registerHealthIndicator: true
        slidingWindowSize: 15
        minimumNumberOfCalls: 10
        failureRateThreshold: 80
        waitDurationInOpenState: 22s
        permittedNumberOfCallsInHalfOpenState: 7
        automaticTransitionFromOpenToHalfOpenEnabled: true
      authServiceCircuit:
        baseConfig: vehicleServiceCircuit

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics