server:
  port: 8102
  forward-headers-strategy: framework

spring:
  main:
    lazy-initialization: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authService
          uri : http://localhost:8103
          predicates:
            - Path=/v1/auth/admin/**, /v1/auth/user/** , /internal/auth/**
          filters:
            - name: DedupeResponseHeader
              args:
                name: Access-Control-Allow-Origin
                strategy: RETAIN_FIRST
        - id: loggingService
          uri : http://localhost:8104
          predicates:
            - Path=/v1/user/notifications/**, /v1/admin/notifications/**, ,/v1/sse/**, /v1/user/tracking/** , /internal/logs/**
          filters:
            - name: DedupeResponseHeader
              args:
                name: Access-Control-Allow-Origin
                strategy: RETAIN_FIRST
        - id: dispatchService
          uri : http://localhost:8105
          predicates:
            - Path=/v1/admin/dispatch/**, /v1/user/dispatch/** , /internal/dispatch/**
          filters:
            - name: DedupeResponseHeader
              args:
                name: Access-Control-Allow-Origin
                strategy: RETAIN_FIRST
        - id: vehicleService
          uri: http://localhost:8106
          predicates:
            - Path=/v1/admin/vehicle/**, /v1/user/vehicle/** , /internal/vehicles/**
          filters:
            - name: DedupeResponseHeader
              args:
                name: Access-Control-Allow-Origin
                strategy: RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "PATCH"
              - "OPTIONS"
            allowed-headers:
              - "Content-Type"
              - "Authorization"
              - "X-Requested-With"
              - "Origin"
              - "Accept"
              - "X-XSRF-TOKEN"
            allow-credentials: true
            exposed-headers:
              - "Set-Cookie"
              - "Authorization"
            max-age: 3600





auth:
  api:
    key : internalKey
  jwt:
    secret: 431da76bdce7104b0a69902ede07459b0087f110d969fb15fef07afc899012ac07bc3435d063f8619c1523d917e84024ee8784c3f2e619c1efb770d86221bf35
    expiration: 604800000
    issuer: auth-service


logging:
  level:
    org.springframework.security: DEBUG
    com.example.UserService: DEBUG