server:
  port: 8101
  address: 0.0.0.0

spring :
  application :
    name : eureka-server


eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  server :
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_LINK:http://eureka-server:8101}/eureka
